version: "3"
services:
  client:
    build: ./client
    container_name: "app-client"
    image: app-client
    restart: always
    ports:
        - "3000:80"
    volumes:
        - ./client:/client
        - /client/node_modules
    links:
        - server
    networks:
        - webappnetwork

  server:
    build: ./client
    container_name: "app-server"
    image: app-server
    restart: always
    ports:
        - "9000:9000"
    volumes:
        - ./server:/server
        - /server/node_modules
    depends_on:
        - mongodb
    networks:
        - webappnetwork

  mongodb: 
    image: mongo
    restart: always
    container_name: mongodb
    # volumes:
    #     - ./data-node:/data/db
    ports:
        - 27017:27017
    command: mongod --noauth --smallfiles
    networks:
        - webappnetwork

networks:
    webappnetwork:
        driver: bridge