version: "3"
services:
  client:
    build: ./client
    container_name: "app-client"
    image: project21/webapp:app-client
    restart: always
    ports:
        - "80:80"
    volumes:
        - ./client:/client
        - /client/node_modules
    links:
        - server
    networks:
        - webappnetwork

  server:
    build: ./server
    container_name: "app-server"
    image: project21/webapp:app-server
    restart: always
    ports:
        - "9000:9000"
    volumes:
        - ./server:/server
        - /server/node_modules
    depends_on:
        - mongodb
    networks:
        - webappnetwork

  mongodb: 
    image: mongo
    restart: always
    container_name: mongodb
    # volumes:
    #     - ./data-node:/data/db
    ports:
        - 27017:27017
    command: mongod --noauth --smallfiles
    networks:
        - webappnetwork

  mysql:
    image: mysql
    restart: always
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    networks:
        - webappnetwork
    environment:
        MYSQL_HOST: localhost
        MYSQL_USER: rootie
        MYSQL_PASSWORD: rootie
        MYSQL_ROOT_PASSWORD: rootie
        MYSQL_DATABASE: p21_main



networks:
    webappnetwork:
        driver: bridge